// <auto-generated />
using System;
using ClinicalExaminationService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClinicalExaminationService.Migrations
{
    [DbContext(typeof(ClinicalExamDbContext))]
    partial class ClinicalExamDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClinicalExaminationService.Model.AssignmentSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClinicRoom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NurseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ShiftType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AssignmentSchedules");
                });

            modelBuilder.Entity("ClinicalExaminationService.Model.ExaminationIcd10", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExaminationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Icd10Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Icd10Code");

                    b.HasIndex("ExaminationId", "Icd10Code")
                        .IsUnique();

                    b.ToTable("ExaminationIcd10s");
                });

            modelBuilder.Entity("ClinicalExaminationService.Model.FollowUpAppointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClinicalNotes")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FollowUpDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VisitId");

                    b.ToTable("follow_up_appointments", (string)null);
                });

            modelBuilder.Entity("ClinicalExaminationService.Model.Icd10Catalog", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Code");

                    b.ToTable("Icd10Catalogs");

                    b.HasData(
                        new
                        {
                            Code = "A00",
                            Description = "Bệnh tả"
                        },
                        new
                        {
                            Code = "A01",
                            Description = "Bệnh thương hàn và phó thương hàn"
                        },
                        new
                        {
                            Code = "A02",
                            Description = "Nhiễm trùng do Salmonella khác"
                        },
                        new
                        {
                            Code = "A09",
                            Description = "Tiêu chảy và viêm dạ dày ruột do nhiễm khuẩn"
                        },
                        new
                        {
                            Code = "A15",
                            Description = "Lao phổi, xác nhận bằng nuôi cấy vi khuẩn"
                        },
                        new
                        {
                            Code = "A16",
                            Description = "Lao phổi, không xác nhận bằng vi khuẩn học"
                        },
                        new
                        {
                            Code = "B01",
                            Description = "Thủy đậu"
                        },
                        new
                        {
                            Code = "B15",
                            Description = "Viêm gan siêu vi A"
                        },
                        new
                        {
                            Code = "B16",
                            Description = "Viêm gan siêu vi B cấp tính"
                        },
                        new
                        {
                            Code = "B34",
                            Description = "Nhiễm virus, chưa xác định vị trí"
                        },
                        new
                        {
                            Code = "E10",
                            Description = "Đái tháo đường type 1"
                        },
                        new
                        {
                            Code = "E11",
                            Description = "Đái tháo đường type 2"
                        },
                        new
                        {
                            Code = "E14",
                            Description = "Đái tháo đường, không đặc hiệu"
                        },
                        new
                        {
                            Code = "F32",
                            Description = "Giai đoạn trầm cảm"
                        },
                        new
                        {
                            Code = "G40",
                            Description = "Động kinh"
                        },
                        new
                        {
                            Code = "I10",
                            Description = "Tăng huyết áp nguyên phát (Huyết áp cao)"
                        },
                        new
                        {
                            Code = "I20",
                            Description = "Đau thắt ngực"
                        },
                        new
                        {
                            Code = "I21",
                            Description = "Nhồi máu cơ tim cấp tính"
                        },
                        new
                        {
                            Code = "I50",
                            Description = "Suy tim"
                        },
                        new
                        {
                            Code = "J00",
                            Description = "Viêm mũi họng cấp tính (Cảm lạnh thông thường)"
                        },
                        new
                        {
                            Code = "J06",
                            Description = "Nhiễm trùng đường hô hấp trên cấp tính, không đặc hiệu"
                        },
                        new
                        {
                            Code = "J18",
                            Description = "Viêm phổi, vi sinh vật không đặc hiệu"
                        },
                        new
                        {
                            Code = "J45",
                            Description = "Hen phế quản (Asthma)"
                        },
                        new
                        {
                            Code = "K21",
                            Description = "Bệnh trào ngược dạ dày thực quản (GERD)"
                        },
                        new
                        {
                            Code = "K29",
                            Description = "Viêm dạ dày và tá tràng"
                        },
                        new
                        {
                            Code = "K35",
                            Description = "Viêm ruột thừa cấp tính"
                        },
                        new
                        {
                            Code = "M54",
                            Description = "Đau lưng (Dorsalgia)"
                        },
                        new
                        {
                            Code = "N39",
                            Description = "Rối loạn khác của đường tiết niệu"
                        },
                        new
                        {
                            Code = "R50",
                            Description = "Sốt không rõ nguyên nhân"
                        },
                        new
                        {
                            Code = "Z00",
                            Description = "Khám sức khỏe tổng quát"
                        });
                });

            modelBuilder.Entity("ClinicalExaminationService.Model.MedicalExamination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExaminedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VisitId")
                        .IsUnique();

                    b.ToTable("MedicalExaminations");
                });

            modelBuilder.Entity("ClinicalExaminationService.Model.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DispenseStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VisitId");

                    b.ToTable("prescriptions", (string)null);
                });

            modelBuilder.Entity("ClinicalExaminationService.Model.PrescriptionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("PrescriptionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("prescription_items", (string)null);
                });

            modelBuilder.Entity("ClinicalExaminationService.Model.ServiceOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("UnitPriceAtOrder")
                        .HasColumnType("decimal(15,2)");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VisitId");

                    b.ToTable("service_orders", (string)null);
                });

            modelBuilder.Entity("ClinicalExaminationService.Model.VisitRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPriority")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<int>("QueueNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("ReceptionistId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("VisitRecords");
                });

            modelBuilder.Entity("ClinicalExaminationService.Model.VitalSign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BloodPressure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("NurseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Pulse")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Temperature")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("VisitId")
                        .IsUnique();

                    b.ToTable("VitalSigns");
                });

            modelBuilder.Entity("ClinicalExaminationService.Model.ExaminationIcd10", b =>
                {
                    b.HasOne("ClinicalExaminationService.Model.MedicalExamination", "MedicalExamination")
                        .WithMany("ExaminationIcd10s")
                        .HasForeignKey("ExaminationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicalExaminationService.Model.Icd10Catalog", "Icd10Catalog")
                        .WithMany("ExaminationIcd10s")
                        .HasForeignKey("Icd10Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Icd10Catalog");

                    b.Navigation("MedicalExamination");
                });

            modelBuilder.Entity("ClinicalExaminationService.Model.FollowUpAppointment", b =>
                {
                    b.HasOne("ClinicalExaminationService.Model.VisitRecord", "VisitRecord")
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisitRecord");
                });

            modelBuilder.Entity("ClinicalExaminationService.Model.MedicalExamination", b =>
                {
                    b.HasOne("ClinicalExaminationService.Model.VisitRecord", "VisitRecord")
                        .WithOne("MedicalExamination")
                        .HasForeignKey("ClinicalExaminationService.Model.MedicalExamination", "VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisitRecord");
                });

            modelBuilder.Entity("ClinicalExaminationService.Model.Prescription", b =>
                {
                    b.HasOne("ClinicalExaminationService.Model.VisitRecord", "VisitRecord")
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisitRecord");
                });

            modelBuilder.Entity("ClinicalExaminationService.Model.PrescriptionItem", b =>
                {
                    b.HasOne("ClinicalExaminationService.Model.Prescription", "Prescription")
                        .WithMany("PrescriptionItems")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("ClinicalExaminationService.Model.ServiceOrder", b =>
                {
                    b.HasOne("ClinicalExaminationService.Model.VisitRecord", "VisitRecord")
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisitRecord");
                });

            modelBuilder.Entity("ClinicalExaminationService.Model.VitalSign", b =>
                {
                    b.HasOne("ClinicalExaminationService.Model.VisitRecord", "VisitRecord")
                        .WithOne("VitalSign")
                        .HasForeignKey("ClinicalExaminationService.Model.VitalSign", "VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisitRecord");
                });

            modelBuilder.Entity("ClinicalExaminationService.Model.Icd10Catalog", b =>
                {
                    b.Navigation("ExaminationIcd10s");
                });

            modelBuilder.Entity("ClinicalExaminationService.Model.MedicalExamination", b =>
                {
                    b.Navigation("ExaminationIcd10s");
                });

            modelBuilder.Entity("ClinicalExaminationService.Model.Prescription", b =>
                {
                    b.Navigation("PrescriptionItems");
                });

            modelBuilder.Entity("ClinicalExaminationService.Model.VisitRecord", b =>
                {
                    b.Navigation("MedicalExamination");

                    b.Navigation("VitalSign");
                });
#pragma warning restore 612, 618
        }
    }
}
